In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
! pip install git+https://github.com/huggingface/transformers@master

In [ ]:
! pip install torch

In [ ]:
# 구글 드라이브에서 모델, 토크나이저 불러오기
from transformers import BertTokenizerFast, GPT2LMHeadModel

model = GPT2LMHeadModel.from_pretrained('/content/gdrive/MyDrive/model_save/model_batch1')

tokenizer = BertTokenizerFast.from_pretrained('/content/gdrive/MyDrive/model_save/model_batch1')
input_ids = tokenizer.encode("text to tokenize")[1:]  # CLS token 제거

In [ ]:
import torch
tokenizer_gpt3 = BertTokenizerFast.from_pretrained("kykim/gpt3-kor-small_based_on_gpt2", 
                                                   bos_token='<|startoftext|>', 
                                                   eos_token='<|endoftext|>', 
                                                   pad_token='<|pad|>')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

Downloading:   0%|          | 0.00/344k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/82.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/615 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'BertTokenizer'.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'BertTokenizerFast'.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
model.eval()

def coverletter_generator(text):
  prompt = f"<|startoftext|> {text}"
  generated = torch.tensor(tokenizer_gpt3.encode(prompt)[1:]).unsqueeze(0)
  generated = generated.to(device)

  print(generated)

  sample_outputs = model.generate(
                                  generated, 
                                  do_sample=True,   
                                  top_k=50, 
                                  max_length = 500,
                                  top_p=0.95, 
                                  num_return_sequences=3,
                                  repetition_penalty=1.1
                                  )

  for i, sample_output in enumerate(sample_outputs):
    result = "{}: {}\n\n".format(i, tokenizer_gpt3.decode(sample_output, skip_special_tokens=True))
    print(result)
  return

In [ ]:
coverletter_generator('저의 강점은 ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 16972, 38964,  8078,     3]])
0: 저의 강점은 식품영양학과 진학 후 처음으로 접한 과목이 식품프로그래밍이었습니다. 교수님께서는 식자재유통업체에서 아르바이트를 하고 있는 학생들을 대상으로 하는 식품영양학과의 수업에선 어떻게 하면 학생들이 식품에 흥미를 가질 수 있을까라는 문제를 알려주셨습니다. 대부분의 학생들이 학년인 저학년들이라 음식을 만드는데 어려움과 관심을 갖지 못한 것이 아닐까 생각해보았습니다. 실제로 저는 학년 때 전공과 관련이 없던 식품영양학을 배우면서 식품에 대해 흥미를 갖게 되었습니다. 이후 전공과목을 더욱 깊이 공부하여 졸업 작품까지 완성해 나갔습니다. 또한 제가 식품영양과에 지원하게 된 가장 큰 이유입니다. 특히 이 직무를 잘 수행하기 위해선 무엇보다 식품에서 필요로 하는 영양성분에 대한 이해도가 필수라고 생각했습니다. 이는 지금까지의 경험 중 식품영양학에 대한 이해도를 가장 높여 줄 것으로 생각합니다. 저는 영양사 자격증을 따기 위해 조리기능장 수업을 신청하였고 약 시간의 짧은 시간에 식품의 전반적인 조리과정을 학습할 수 있었습니다. 또한 식품기사 필기 합격률 를 달성하며 전공성적 또한 합격할 수 있었습니다. 이러한 경험을 통해 저는 식품을 올바르게 이해하고자 하는 태도를 가질 수 있었으며 이는 품질관리 업무를 담당하기에 더욱 적합하다고 생각하였습니다. 제 인생의 가치관은 한 번 더 생각하는 삶입니다. 살면서 아무리 우수한 식당도 그 맛의 정도와 식재료의 상태가 좋지 않다면 그 음식은 고객의 마음을 사로잡지 못하는 것 같습니다. 하지만 이를 개선하고자 항상 노력하며 살다 보니 새로운 분야에서 일을 시작하게 되면 먼저 그 식당을 방문하고 지인들께 정보를 얻어서 저만의 레시피를 익히고 직접 요리를 만들어 보기도 합니다. 이렇듯 저는 늘 좋은 결과를 얻을 수 있다고 생각하며 살아왔습니다. 하지만 이러한 저의 가치관이 조금 더 발전된 삶을 살고 싶다는 생각을 가지게 했습니다. 그래서 저는 한번 더

In [ ]:
coverletter_generator('저는 자료를 분석하는 능력이 강합니다. ')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 14156, 21992, 15626, 13975, 21561,  2122, 14015,  2016,     3]])
0: 저는 자료를 분석하는 능력이 강합니다. 이러한 장점으로 입사 후 자료 수집 및 분석을 통한 데이터 분석의 중요성 및 개선점 파악에 힘쓰겠습니다. 이를 위해서는 정확한 데이터 분석능력이 필요합니다. 다양한 팀 프로젝트 경험은 저의 강점이며 이러한 역량을 바탕으로 다양한 팀 프로젝트를 진행하였습니다. 대학 강의 중 자료 분석을 통하여 팀 프로젝트를 수행한 적이 있습니다. 이러한 경험을 통해 분석능력을 길렀습니다. oo연구개발협력센터 인턴을 수행하며 기안서 작성 및 연구 방향 제시를 담당하였습니다. 관련 부서의 요청이 있을 경우 이를 토대로 자료를 검토 및 수정하였습니다. 그리고 학회 발표의 주 역할을 맡아 조원들과 소통하고 정보를 공유했습니다.


1: 저는 자료를 분석하는 능력이 강합니다. 이러한 역량으로 대학교 학년 때 교내 학술대회에서 최우수상을 수상한 적이 있습니다. 이 대회를 준비한 이유는 교수님께서 년 월에 설립하신 회사에 다닌다고 말씀하셨기 때문입니다. 저는 대학원에서 oooo와 관련된 프로젝트를 한 경험이 있습니다. 년 월에 한국정보처리학회에서 주최하는 oooo의 oo oooo에 참가하여 명의 학우들이 만든 작품을 전시하고 싶었습니다. 당시 연구실에서의 연구는 대부분 컴퓨터를 다루고 있는 학생 위주로 구성되어 있었습니다. 하지만 전시회를 준비하는 입장이었기 때문에 이러한 학생들을 위해 컴퓨터 잡지를 참고하여 프로그래밍된 작품들을 전시하였습니다. 또한 프로그래밍 과목을 통해 컴퓨터 프로그래밍을 경험할 수 있었습니다. 이렇게 저희 작품은 저의 흥미를 끌었습니다. 이후 대학교 학년에는 컴퓨터 프로그래밍 동아리 팀장과 함께 프로그래밍 공모전에 도전해 우수상을 받는 쾌거를 이루었습니다. 그 결과 oooo의 소프트웨어 공모전 우수상인 oooo 캡스톤디자인 경진대회에 참가할 기회를 얻었습니다. 이처럼 통계분석 능력

In [ ]:
coverletter_generator('저의 강점은 소통입니다.')

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


tensor([[42000, 16972, 38964,  8078, 20312, 13992,  2016,     3]])
0: 저의 강점은 소통입니다. 제 장점은 항상 상대방의 이야기를 잘 들어주고 공감해주려는 태도입니다. 그래서 다른 사람들에게 긍정적인 기운을 전파해 줄 수 있습니다. 또 이 장점으로 인해 타인을 배려할 줄 알며 남에게 힘이 되어주는 역할을 해낼 수 있었습니다.


1: 저의 강점은 소통입니다. 소통능력은 다양한 사람들과의 소통을 통해 좋은 방향으로 나아갈 수 있다고 생각합니다. 저는 대학생활 중 많은 사람을 만나며 소통 능력을 길렀습니다. 이러한 경험을 바탕으로 일원이 되어 보다 좋은 서비스를 제공하고 싶습니다. 이를 위해 먼저 사람들과 원활히 소통할 방법을 찾았습니다. 우선 매주 월요일에 모여서 학교 축제를 홍보하는 동아리 활동을 했습니다. 특히 년 동안 꾸준히 활동해온 동아리는 다양한 사람들 그리고 서로 간의 정보를 공유하는 창구가 되었습니다. 또한 동아리 부회장으로서도 소통하며 많은 사람들과 친해졌습니다. 이를 활용하여 더욱 활성화된 동아리가 될 수 있도록 노력하겠습니다. 마지막으로 다양한 사람들을 만났습니다. 년 때 한 친구가 저희 동아리를 소개하지 않았습니다. 이 사실을 알고 있었던 저는 동아리 홍보를 하기 위해 직접 연락해 도움을 요청했습니다. 동아리원들의 연락처를 알려주고 함께 이야기 나눌 수 있는 자리를 마련해주었습니다. 결국 두 친구와 잘 어울리면서 동아리를 알릴 수 있었습니다. 입사 후에도 고객과 마주하는 영업 사원으로서 열린 마음으로 동료들과 협력하고 고객의 소리를 듣고 문제점을 찾아내고 개선점을 만들어가는 신입사원이 되겠습니다.


2: 저의 강점은 소통입니다. 대학교 학년 때 교환학생을 다녀왔습니다. 이 경험으로 저는 다양한 사람들을 만날 수 있었고 그에 대한 이해도가 높다는 것을 깨달았습니다. 또한 저는 사람들과의 소통을 통해 상대방의 의견을 듣고 존중하는 것의 중요성을 배웠습니다. 교환학생 생활을 하며 다양한 사람들